# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - nightly

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

addons:
  apt:
    packages:
    - gnuplot
    - imagemagick

before_script:  # NetCDF is not required, but test its dependent functions anyway
  - julia -e 'VERSION >= v"0.7" && (import Pkg; Pkg.add("NetCDF"); Pkg.build("NetCDF"))'

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.build("Granular"); Pkg.test("Granular"; coverage=true)';

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

matrix:
  allow_failures:
  - julia: nightly
