# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

notifications:
  email:
    on_success: never  # default: change
    on_failure: always # default: always

addons:
  apt:
    packages:
    - gnuplot
    - imagemagick

matrix:
  allow_failures:
  - julia: nightly

stages:  # Set order of stages
  - test
  - docs

jobs:
  include:
    - stage: test
      os:
        - linux
        - osx
      julia:
        - 1.0
        - nightly
      before_script:  # NetCDF is an optional dependency
        - julia -e 'VERSION >= v"0.7" && (import Pkg; Pkg.add("NetCDF");
                    Pkg.build("NetCDF"))'
      script:
        - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
        - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.build("Granular");
                    Pkg.test("Granular"; coverage=true)';
      after_success:
        - julia -e 'import Pkg; cd(Pkg.dir("Granular"));
                    Pkg.add("Coverage"); using Coverage;
                    Codecov.submit(process_folder())'
    - stage: docs
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
